### ISSUE TITLE
request rejected error with plugin

### ISSUE THREAD

**Issue by pponce** [luisiam/homebridge-liftmaster2#18]
I'm getting the following error that crashes homebridge.
undefined:1
<html><head><title>Request Rejected</title></head><body>Your request has been denied.<br><br>[5442595389186517041]</body></html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at Request._callback (/home/pi/.nvm/versions/node/v6.9.1/lib/node_modules/homebridge-liftmaster2/index.js:249:23)
    at Request.self.callback (/home/pi/.nvm/versions/node/v6.9.1/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/pi/.nvm/versions/node/v6.9.1/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/pi/.nvm/versions/node/v6.9.1/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Started happening today. Is chamberlain now rejecting API access?
If i remove this plugin homebridge loads up fine.

**Comment by pponce** [comment]
I just noticed this same error is being discussed in issue #15

**Comment by ktgeek** [comment]
I saw this starting about 7 hours ago as well

**Comment by reallybman** [comment]
how do I remove the plugin?>

**Comment by pponce** [comment]
to remove it i had to:
Remove the config parameters in Config.json
i also had to go into the accessories folder and edit the cachedAccessories file.
It's a bit tricky so i did 
tail -f cachedAccessories
Copied the output into my favorite text editor (notpad++). should all be on one line.
I then did a find and replace for 
{"plugin":
replaced with
\n{"plugin":
Deleted the line that contained the liftmaster2 reference.
I put everything back into one line and replaced the original content of cachedAccessories with the edited content.

that let me run homebridge and removed the opener from the list of accessories.

**Comment by pponce** [comment]
Looks like this endpoint is down.  
myqexternal.myqdevice.com
Maybe Chamberlain shut it down for good?
Hopefully there is a workaround as their official iOS app still works.

**Comment by amitgandhinz** [comment]
I just tried logging in via the app and my credentials were rejected.  Also tried to log in via lift master.com and it rejected my password.  Forgot password yields 'Unknown User'.  I suspect they could be having API issues.

**Comment by rd9082** [comment]
I know they are releasing official HomeKit compatible devices in April. Wonder if that has anything to do with them shutting this down (I know nothing about APIs so I I'm just guessing). Hopefully we won't have to resort to buying their $50 gateway

**Comment by pponce** [comment]
If it has anything to do with it i hope it's just a new end point url to use.
Could be related though.

**Comment by solomonj1963** [comment]
If it helps, wanted to report that the homebridge-chamberlain plug is still working.

**Comment by drgrabowski** [comment]
Glad I'm not the only one having this issue. Do we just need to change the API?

**Comment by amitgandhinz** [comment]
from the slack #random channel:

```
jtomlinson:
uninstalled homebridge-liftmaster2 and installed homebridge-chamberlain. My guess is that the appId used by the former is no longer valid
```

@luisiam have you checked to see if the official lift master app changed their app id?  Since there are reports that chamberlain is still working, and the api calls look similar, the app id used could be the culprit here.

**Comment by pponce** [comment]
I just tried homebridge-liftmaster2 with the homebridge-chamberlain app id and no luck...

**Comment by reallybman** [comment]
Yes - both plugins are using the same url, so it shouldn't work. Really too bad if this cannot come back online.

**Comment by pponce** [comment]
The api function calls used in the homebridge-chamberlain are different.
The authentication uses a different url "myqexternal.myqdevice.com/api/v4/User/Validate".
And it is a post not a get request.
It also has some other api call url's that are different.

This is an unofficial API so it looks like chamberlain just changed the function calls. Deprecated old ones that impacted this plugin.

**Comment by waxlabo** [comment]
Maybe it has something to do with the deviceId?

**Comment by jacobwtyler** [comment]
I'm having the same issue.  I bet Chamberlain is shutting this down for their new homekit hub extension.

**Comment by pponce** [comment]
As other have confirmed i'm also using homebridge-chamberlain plugin with no issues.
My guess is there was a change/clean up in the supported API calls and homebridge-chamberlain is using supported functions while this plugin is using no longer supported api calls.  Because there are no official open API's provided by chamberlain things like this will continue to happen.

**Comment by jacobwtyler** [comment]
Hmmm. The Chamberlain plugin is crashing for me as is the original liftmaster plugin and the myq plugin.  The Chamberlain and LiftMaster plugins appear to be the same code but I get further with the liftmaster one. (It crashes as soon as I check my Door status in home app)

**Comment by pponce** [comment]
Are you sure you removed the liftmaster2 plugin fully? I needed to remove the config and also the cached accessories configuration.  If you uninstall all garage door plugins does homebridge crash when you open the home app?

Get Outlook for iOS<https://aka.ms/o0ukef>

_____________________________

**Comment by jeffqchen** [comment]
I only had to remove the platform part from my config.json

My homebridge stopped crash right after that.

**Comment by jacobwtyler** [comment]
I deleted the accessories and persist folders with no luck. I used to use the original LiftMaster plugin with success but now it crashes too so I just gave up on Garage Door for now but I'm going to give it another shot soon. I was kind of hoping the liftmaster2 plugin might get patched soon. Is that not likely?

**Comment by jeffqchen** [comment]
I just tried and it seems simply editing it out from config.json doesn't work.

I had to uninstall the package in order to stop it from being loaded at startup with this command:
sudo npm -g uninstall homebridge-liftmaster2 --save

**Comment by pponce** [comment]
You definitely have to
1.) uninstall the homebridge-liftmaster2 plugin

npm -g uninstall homebridge-liftmaster2

2.) Remove the config section that you entered into config.json for the liftmaster2 plugin

3.) Remove reference to the cached accessory created by the liftmaster2 plugin.  see my third comment in this thread.

4.) install the homebridge-chamberlain plugin and configure it in config.json

That's what i did to resolve my issues. works great now.
By only doing steps one and two above my home app would crash homebridge on opening up the app.

**Comment by sats4eva** [comment]
@pponce, what version of node are you running to get this all to work?

**Comment by sats4eva** [comment]
I can get the garage doors to show up on my home app but both are showing as "no response". I read somewhere else that somebody got it working by upgrading their node. I'm currently on 6.9.5

**Comment by pponce** [comment]
I had it all working under node 6.9.1.
I just updated to 6.9.5 yesterday after a failed attempt to get homebridge running using 7.5.0.

**Comment by luisiam** [comment]
Please try 0.4.0

**Comment by sats4eva** [comment]
@luisiam sorry 0.4.0 of what?

**Comment by luisiam** [comment]
0.4.0 of the plugin. I just updated it

**Comment by sats4eva** [comment]
I got it work but now when I try to execute it, I get "no response". Very frustrating

**Comment by sats4eva** [comment]
Sorry where do I get it? Is there a link? I'm a newbie to all of this

**Comment by luisiam** [comment]
Just follow the installation procedure on readme

**Comment by sats4eva** [comment]
So I followed all instructions and it still shows on my home app but when I press it, it changes to no response

**Comment by luisiam** [comment]
Please update the plugin and try again.

**Comment by drgrabowski** [comment]
I'm also having the "no response" issue, my logs given an error state, ReturnCode 217, and also says error processing request. I just updated the plugin.

**Comment by drgrabowski** [comment]
Feb 17 15:57:46 the-call-of homebridge: [2/17/2017, 3:57:46 PM] Error setting Enterprise Bay state: {"ReturnCode":"217","ErrorMessage":"Error processing request (217)","CorrelationId":"<string>"}

I'm not sure if the <string> is random or an identifier, so I edited it out.

**Comment by luisiam** [comment]
I just forgot to stringify the body when I execute the put request. Should be fixed now.

**Comment by sats4eva** [comment]
I get the same error. I'm going to update and try again

Sent from my iPhone

On Feb 17, 2017, at 4:57 PM, drgrabowski <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm also having the "no response" issue, my logs given an error state, ReturnCode 217, and also says error processing request. I just updated the plugin.

**Comment by sats4eva** [comment]
I upgraded to 0.4.2 and still get the same error.
Returncode 217

Sent from my iPhone

On Feb 17, 2017, at 4:59 PM, Luis Iam <notifications@github.com<mailto:notifications@github.com>> wrote:


I just forgot to stringify the body when I execute the put request. Should be fixed now.

**Comment by drgrabowski** [comment]
It's working for me after I update the plugin. Thanks!!!

**Comment by sats4eva** [comment]
Yes that is what I updated to but still get error.

Sent from my iPhone

On Feb 17, 2017, at 5:05 PM, Luis Iam <notifications@github.com<mailto:notifications@github.com>> wrote:


Latest plugin version is 0.4.1 only

**Comment by luisiam** [comment]
Try to remove the plugin completely following the removal procedure and install it again.

**Comment by drgrabowski** [comment]
I just did a npm install of the plugin, update never seems to work.

**Comment by luisiam** [comment]
Never use update. Always use install

**Comment by drgrabowski** [comment]
Good to know :)

**Comment by sats4eva** [comment]
Ok guys I did a complete removal of both the plugin and homebridge from my app. Reinstall and all is working. Thank you very much!!!

Sent from my iPhone

On Feb 17, 2017, at 5:37 PM, drgrabowski <notifications@github.com<mailto:notifications@github.com>> wrote:


Good to know :)

**Comment by ktgeek** [comment]
Just wanted to report 0.4.1 is working perfectly for me!  Thanks, luisiam!

**Comment by waxlabo** [comment]
I am still not having any luck with using homebridge-liftmaster2,

I keep getting:

undefined:1
<html><head><title>Request Rejected</title></head><body>Your request has been denied.<br><br>[5442595389335701192]</body></html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/local/lib/node_modules/homebridge-liftmaster2/index.js:249:23)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:1001:12)
    at Object.onceWrapper (events.js:290:19)

**Comment by sats4eva** [comment]
Try to uninstall lift master2 all together and re install. I think it's using your old plugin still
Ensure you have version 0.4.1

Sent from my iPhone

On Feb 18, 2017, at 12:02 PM, waxlabo <notifications@github.com<mailto:notifications@github.com>> wrote:


I am still not having any luck with using homebridge-liftmaster2,

I keep getting:

undefined:1

<title>Request Rejected</title>Your request has been denied.

[5442595389335701192] ^

SyntaxError: Unexpected token < in JSON at position 0
at JSON.parse ()
at Request._callback (/usr/local/lib/node_modules/homebridge-liftmaster2/index.js:249:23)
at Request.self.callback (/usr/local/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:186:22)
at emitTwo (events.js:106:13)
at Request.emit (events.js:191:7)
at Request. (/usr/local/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:1081:10)
at emitOne (events.js:96:13)
at Request.emit (events.js:188:7)
at IncomingMessage. (/usr/local/lib/node_modules/homebridge-liftmaster2/node_modules/request/request.js:1001:12)
at Object.onceWrapper (events.js:290:19)

**Comment by waxlabo** [comment]
How do I check what version I am on?  I uninstalled liftmaster2 and homebridge and installed both from scratch.

**Comment by sats4eva** [comment]
When you install the new version it will say v 0.4.1 after it's done installing

Sent from my iPhone

On Feb 18, 2017, at 12:25 PM, waxlabo <notifications@github.com<mailto:notifications@github.com>> wrote:


How do I check what version I am on? I uninstalled liftmaster2 and homebridge and installed both from scratch.

**Comment by dishguy** [comment]
liftmaster2 works great on MacBook running home bridge... but when I try to run it on raspberry pi zero W I get the error above... removed it from Pi and reinstalled it and get same error... removed it from Mac and reinstalled it on pi same error... reinstalled it on Mac runs perfectly.... I'm missing something... any suggestions?? would love to get the last item working to utilize the pi as my low power bridge and free up my Mac
